cd opencv
del /s /q out
mkdir out
cd out

mkdir Release
cd Release
cmake -DCMAKE_INSTALL_PREFIX=install -DBUILD_SHARED_LIBS=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_WITH_STATIC_CRT=OFF -DOPENCV_DNN_OPENCL=OFF -DWITH_QUIRC=OFF -DWITH_PROTOBUF=OFF -DWITH_OPENJPEG=OFF -DWITH_WEBP=OFF -DWITH_OPENEXR=OFF -DWITH_PNG=OFF -DWITH_TIFF=OFF -DWITH_JASPER=OFF -DWITH_JPEG=OFF -DWITH_GSTREAMER=OFF -DWITH_FFMPEG=OFF -DBUILD_LIST=core,highgui  ../..
cmake --build . --config Release --target install
cd ..

mkdir Debug
cd Debug
cmake -DCMAKE_INSTALL_PREFIX=install -DBUILD_SHARED_LIBS=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_WITH_STATIC_CRT=OFF -DOPENCV_DNN_OPENCL=OFF -DWITH_QUIRC=OFF -DWITH_PROTOBUF=OFF -DWITH_OPENJPEG=OFF -DWITH_WEBP=OFF -DWITH_OPENEXR=OFF -DWITH_PNG=OFF -DWITH_TIFF=OFF -DWITH_JASPER=OFF -DWITH_JPEG=OFF -DWITH_GSTREAMER=OFF -DWITH_FFMPEG=OFF -DBUILD_LIST=core,highgui  ../..
cmake --build . --config Debug --target install
cd ..

cd ..

cd ..
