#!/bin/bash

echo "Charming detector connection configuration."

FILE=/etc/CHARMing/charmsystem.json

if [ -f $FILE ] || [ -f /etc/CHARMing/mesytecsystem.json ];
then
  printf "Keeping existing configuration.\n"
else
  cp /etc/CHARMing/examples/erwin.json  $FILE
  if [ $? -ne 0 ]
  then
    printf "\n"
  else
    printf "creating configuration $FILE \n"
  fi

fi


